mybatis:
  mapper-locations: mapper/*.xml

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver
    sql-script-encoding: UTF-8
    schema:
      - classpath:init/app_user.sql
    initialization-mode: embedded
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 6000
      validation-query: select 1



