spring:
  profiles:
    active: boot

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver
    sql-script-encoding: UTF-8
    schema:
      - classpath:init/app_user.sql
      - classpath:init/app_address.sql
      - classpath:init/app_phone.sql
    initialization-mode: embedded
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 6000
      validation-query: select 1;

  h2:
    console:
      enabled: true
      path: /h2

# 设置tomcat相关信息
server:
  tomcat:
    max-threads: 1000 # 默认200
    max-connections: 10000 # 默认10000